/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

//import fruta.Pogo;
import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.SwingUtilities;

/**
 *
 * @author Alumno
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();

//        p=po;
    }

    public void iniciar(boolean connSt) {
        this.setConnStatus(connSt);
       // this.habilitarBotones(connSt);
        this.setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelConn = new javax.swing.JLabel();
        jLabelJ1 = new javax.swing.JLabel();
        jLabelJ2 = new javax.swing.JLabel();
        jButtonDale = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jButtonTablas = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jCheckBoxTurbo = new javax.swing.JCheckBox();
        jButtonSetup = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        setPreferredSize(new java.awt.Dimension(400, 400));
        setResizable(false);

        jLabelTitulo.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 153, 0));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("POGO");

        jLabelConn.setText("jLabel2");

        jLabelJ1.setText("Jugador1");

        jLabelJ2.setText("Jugador2");

        jButtonDale.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonDale.setText("DALE POGO!");
        jButtonDale.setMaximumSize(new java.awt.Dimension(110, 25));
        jButtonDale.setMinimumSize(new java.awt.Dimension(110, 25));
        jButtonDale.setPreferredSize(new java.awt.Dimension(110, 25));

        jProgressBar1.setStringPainted(true);

        jProgressBar2.setStringPainted(true);

        jButtonTablas.setText("Tablas");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 0, null, 1));

        jCheckBoxTurbo.setText("Turbo");

        jButtonSetup.setText("Setup");

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 0));
        jLabel1.setText("---");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("---");

        jLabel3.setText("Cantidad de pogos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelConn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSetup)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonTablas)
                        .addGap(40, 40, 40))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelJ2)
                                .addGap(87, 87, 87))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxTurbo)
                                    .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jButtonDale, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jCheckBoxTurbo)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJ1)
                    .addComponent(jLabelJ2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addGap(33, 33, 33)
                .addComponent(jButtonDale, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSetup)
                    .addComponent(jButtonTablas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelConn)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainMenu().setVisible(true);
//            }
//        });
//    }
    public void setPB1Value(int v) {
        jProgressBar1.setValue(v);
        jProgressBar1.setString(v + "");
    }

    public void setPB2Value(int v) {
        jProgressBar2.setValue(v);
        jProgressBar2.setString(v + "");
    }
    
    public void setLabelText(String t, int i) {
        if (i==0)  this.jLabel1.setText(t);
        if (i==1) this.jLabel2.setText(t);
    }
    
//    public void setLabel2Text(String t) {
//        this.jLabel2.setText(t);
//    } mhhhhhhhhhhhhhhhhhhhh
    
    /* metodos para el color del crit
    public void setLabel1Text(String t, Color c) {
        this.jLabel1.setForeground(c);
        this.jLabel1.setText(t);
    }
    
    public void setLabel2Text(String t, Color c) {
        this.jLabel1.setForeground(c);
        this.jLabel2.setText(t);
    }*/

    public void setConnStatus(boolean c) {
        habilitarBotones(c);
        if (c) {
            jLabelConn.setText("CONECTADO A SERVIDOR SQL");
            jLabelConn.setForeground(Color.GREEN);
        } else {
            jLabelConn.setText("NO CONECTADO A SERVIDOR SQL");
            jLabelConn.setForeground(Color.RED);
        }
    }
    
    public void habilitarBotones(boolean c) {
        
        jButtonDale.setEnabled(c);
        jButtonTablas.setEnabled(c);
    }

    public boolean getTurbo() {
        return jCheckBoxTurbo.isSelected();
    }

    public void addTablasHandler(ActionListener a) {
        jButtonTablas.addActionListener(a);
    }

    public void addDaleHandler(ActionListener a) {
        jButtonDale.addActionListener(a);
    }
    
    public void addSetupHandler (ActionListener a) {
        jButtonSetup.addActionListener(a);
    }

    public void elegirBuachos(String n1, String n2, int hp1, int hp2) {
//        SwingUtilities.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//        System.out.println("precambios");
        jLabelJ1.setText(n1);
        jLabelJ2.setText(n2);
        jProgressBar1.setMaximum(hp1);
        jProgressBar1.setValue(hp1);
        jProgressBar1.setString(hp1 + "");
        jProgressBar2.setMaximum(hp2);
        jProgressBar2.setValue(hp2);
        jProgressBar2.setString(hp2 + "");

//        System.out.println("postcambios");
//                this.validate();
//                System.out.println("ignore repaint? " + this.getIgnoreRepaint());
        if (!this.getTurbo()) {
            try {
                System.out.println("empieza el sleep");
                Thread.sleep(300);
            } catch (InterruptedException e) {

            }
        } else {
            try {
                System.out.println("empieza el sleep");
                Thread.sleep(10);
            } catch (InterruptedException e) {

            }
        }

//        System.out.println("termina el sleep");
//            }
//        });
    }

    public int getCantidadDeVeces() {
        try {
            jSpinner1.commitEdit();
        } catch (java.text.ParseException e) {
        }
        return (Integer) jSpinner1.getValue();
    }

    public void cambiarCantidadDeVeces(int veces) {
        jSpinner1.setValue(veces);
    }
    
    public void cambiarColorPersonajes(int v) {
        switch(v){
            case 0: jLabelJ1.setForeground(Color.black);
                    jLabelJ2.setForeground(Color.black);
                    break;
            case 1: jLabelJ1.setForeground(Color.YELLOW);
                    jLabelJ2.setForeground(Color.RED);
                    break;
            case 2: jLabelJ1.setForeground(Color.RED);
                    jLabelJ2.setForeground(Color.YELLOW);
                    break;
            case 3: jLabelJ1.setForeground(Color.BLUE);
                    jLabelJ2.setForeground(Color.BLUE);
                    break;
        }
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDale;
    private javax.swing.JButton jButtonSetup;
    private javax.swing.JButton jButtonTablas;
    private javax.swing.JCheckBox jCheckBoxTurbo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelConn;
    private javax.swing.JLabel jLabelJ1;
    private javax.swing.JLabel jLabelJ2;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
