/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

//import fruta.Pogo;
import java.awt.Color;
import java.awt.event.ActionListener;
import javax.swing.SwingUtilities;

/**
 *
 * @author Alumno
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();

//        p=po;
    }

    public void iniciar(boolean connSt) {
        this.setConnStatus(connSt);
       // this.habilitarBotones(connSt);
        this.setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitulo = new javax.swing.JLabel();
        jLabelConn = new javax.swing.JLabel();
        jLabelJ1 = new javax.swing.JLabel();
        jLabelJ2 = new javax.swing.JLabel();
        jButtonDale = new javax.swing.JButton();
        jProgressBar1 = new javax.swing.JProgressBar();
        jProgressBar2 = new javax.swing.JProgressBar();
        jButtonTablas = new javax.swing.JButton();
        jSpinner1 = new javax.swing.JSpinner();
        jCheckBoxTurbo = new javax.swing.JCheckBox();
        jButtonSetup = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 204, 204));
        setResizable(false);

        jLabelTitulo.setFont(new java.awt.Font("Comic Sans MS", 0, 36)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 153, 0));
        jLabelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitulo.setText("POGO");

        jLabelConn.setText("jLabel2");

        jLabelJ1.setText("Jugador1");

        jLabelJ2.setText("Jugador2");

        jButtonDale.setText("DALE POGO!");

        jProgressBar1.setStringPainted(true);

        jProgressBar2.setStringPainted(true);

        jButtonTablas.setText("Tablas");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(1, 0, null, 1));

        jCheckBoxTurbo.setText("Turbo");

        jButtonSetup.setText("Setup");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(jButtonDale)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jLabelTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelJ1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelJ2)
                        .addGap(94, 94, 94))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelConn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCheckBoxTurbo)
                        .addGap(66, 66, 66))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(jButtonSetup)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonTablas)
                            .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConn)
                    .addComponent(jCheckBoxTurbo))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelJ1)
                    .addComponent(jLabelJ2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jProgressBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonDale)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTablas)
                    .addComponent(jButtonSetup))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainMenu().setVisible(true);
//            }
//        });
//    }
    public void setPB1Value(int v) {
        jProgressBar1.setValue(v);
        jProgressBar1.setString(v + "");
    }

    public void setPB2Value(int v) {
        jProgressBar2.setValue(v);
        jProgressBar2.setString(v + "");
    }

    public void setConnStatus(boolean c) {
        habilitarBotones(c);
        if (c) {
            jLabelConn.setText("CONECTADO A SERVIDOR SQL");
            jLabelConn.setForeground(Color.GREEN);
        } else {
            jLabelConn.setText("NO CONECTADO A SERVIDOR SQL");
            jLabelConn.setForeground(Color.RED);
        }
    }
    
    public void habilitarBotones(boolean c) {
        
        jButtonDale.setEnabled(c);
        jButtonTablas.setEnabled(c);
    }

    public boolean getTurbo() {
        return jCheckBoxTurbo.isSelected();
    }

    public void addTablasHandler(ActionListener a) {
        jButtonTablas.addActionListener(a);
    }

    public void addDaleHandler(ActionListener a) {
        jButtonDale.addActionListener(a);
    }
    
    public void addSetupHandler (ActionListener a) {
        jButtonSetup.addActionListener(a);
    }

    public void elegirBuachos(String n1, String n2, int hp1, int hp2) {
//        SwingUtilities.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//        System.out.println("precambios");
        jLabelJ1.setText(n1);
        jLabelJ2.setText(n2);
        jProgressBar1.setMaximum(hp1);
        jProgressBar1.setValue(hp1);
        jProgressBar1.setString(hp1 + "");
        jProgressBar2.setMaximum(hp2);
        jProgressBar2.setValue(hp2);
        jProgressBar2.setString(hp2 + "");

//        System.out.println("postcambios");
//                this.validate();
//                System.out.println("ignore repaint? " + this.getIgnoreRepaint());
        if (!this.getTurbo()) {
            try {
                System.out.println("empieza el sleep");
                Thread.sleep(300);
            } catch (InterruptedException e) {

            }
        } else {
            try {
                System.out.println("empieza el sleep");
                Thread.sleep(10);
            } catch (InterruptedException e) {

            }
        }

//        System.out.println("termina el sleep");
//            }
//        });
    }

    public int getCantidadDeVeces() {
        try {
            jSpinner1.commitEdit();
        } catch (java.text.ParseException e) {
        }
        return (Integer) jSpinner1.getValue();
    }

    public void cambiarCantidadDeVeces(int veces) {
        jSpinner1.setValue(veces);
    }
//    private Pogo p;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDale;
    private javax.swing.JButton jButtonSetup;
    private javax.swing.JButton jButtonTablas;
    private javax.swing.JCheckBox jCheckBoxTurbo;
    private javax.swing.JLabel jLabelConn;
    private javax.swing.JLabel jLabelJ1;
    private javax.swing.JLabel jLabelJ2;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JProgressBar jProgressBar2;
    private javax.swing.JSpinner jSpinner1;
    // End of variables declaration//GEN-END:variables
}
